### ISSUE TITLE
Track Out of Date Stuff on OG MINT Site

### ISSUE THREAD

**Issue by priyanshumahey** [UBCMint/UBCMint.github.io#16]

**Comment by priyanshumahey** [comment]
# Track Out of Date Stuff on OG MINT Site
## Overview
Go over the old website and figure out anything that may be out of date. Record this on a google doc (keep it within the MINT Google drive).

## Timeline
This task should be a fairly simple task, taking maximum 2 hours to complete. I'd expect this task to be done in a week (by Oct 9)

## Technical Overview
Not a very technical project. It really just requires going through the site and tracking what needs to be updated in a google doc.

## Submission Guidelines 
Let @priyanshumahey know when you're done and paste the update into the discord

## Comments and Questions
Our old site is:

https://ubcmint.github.io/

For any questions, ask @priyanshumahey

**Comment by mlykwong** [comment]
https://docs.google.com/spreadsheets/d/1AZDNJjRQQgI3cjbg4Vi8yV9z8KVXgldBBbzxCG1Rr2k/edit?usp=sharing
